# Generated by Django 6.0.1 on 2026-01-14 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_classsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid1', models.FloatField(default=0)),
                ('mid2', models.FloatField(default=0)),
                ('presentation', models.FloatField(blank=True, null=True)),
                ('assignment', models.FloatField(blank=True, null=True)),
                ('final', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark', to='core.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
