# Generated by Django 6.0.1 on 2026-01-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_storedfile_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsession',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('completed', 'Attended'), ('absent', 'Absent'), ('cancelled', 'Cancelled'), ('no_attendance', 'No Attendance Taken')], default='planned', max_length=20),
        ),
    ]
