# Generated by Django 6.0.1 on 2026-01-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_sharelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharelink',
            name='cleaned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sharelink',
            name='cleanup_after_hours',
            field=models.PositiveIntegerField(default=24, help_text='Hours after deactivation to clean ZIP'),
        ),
    ]
